name = "MGSchwarzSolver"
uuid = "1f373542-8a5c-11ea-12aa-eb13d5ce787b"
authors = ["Jordan Jalving", "University of Wisconsin-Madison"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
